CREATE DATABASE `SRPDB` DEFAULT CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI;

CREATE TABLE `SRPDB`.`M_CITY` (
`M_CITY_ID` INT( 10 ) NOT NULL ,
`NAME` VARCHAR( 60 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`COUNTRY` VARCHAR( 60 ) NOT NULL ,
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
PRIMARY KEY ( `M_CITY_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`M_LOCALITY` (
`M_LOCALITY_ID` INT( 10 ) NOT NULL ,
`M_CITY_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`NAME` VARCHAR( 60 ) NOT NULL ,
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`ISSUMMARY` CHAR( 1 ) NOT NULL DEFAULT 'N',
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`M_PARENTLOCALITY_ID` INT NOT NULL ,
PRIMARY KEY ( `M_LOCALITY_ID` )
) ENGINE = MYISAM ;


CREATE TABLE `SRPDB`.`M_SUBLOCALITY` (
`M_SUBLOCALITY_ID` INT( 10 ) NOT NULL ,
`M_LOCALITY_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`NAME` VARCHAR( 60 ) NOT NULL ,
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`ISSUMMARY` CHAR( 1 ) NOT NULL DEFAULT 'N',
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`M_PARENTSUBLOC_ID` INT NOT NULL ,
PRIMARY KEY ( `M_SUBLOCALITY_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`M_UOM` (
`M_UOM_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`NAME` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`STDPRECISION` INT( 1 ) NOT NULL DEFAULT '0',
`ABBREVATION` CHAR( 3 ) NOT NULL ,
`DESCRIPTION` VARCHAR( 255 ) NULL ,
PRIMARY KEY ( `M_UOM_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`M_PRODUCTCATEGORY` (
`M_PRODUCTCATEGORY_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`NAME` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
PRIMARY KEY ( `M_PRODUCTCATEGORY_ID` )
) ENGINE = MYISAM ;


CREATE TABLE `SRPDB`.`M_PRODUCT`(
`M_PRODUCT_ID` INT(10) NOT NULL,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`CODE` VARCHAR( 60 ) NOT NULL ,
`NAME` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`M_PRODUCTCATEGORY_ID` INT( 10 ) NOT NULL ,
`M_UOM_ID` INT( 10 ) NOT NULL ,
`PRODUCTTYPE` CHAR(1) NOT NULL,
`UPC_EAN` VARCHAR( 255 ) NULL ,
`IMAGEPATH` VARCHAR( 255 ) NULL ,
`PURCHASEPRICE` DOUBLE (15,5) DEFAULT 0,
`SELLINGPRICE` DOUBLE (15,5) DEFAULT 0,
`CURRENTQTY` DOUBLE (15,5) DEFAULT 0,
`CURRENTCOST` DOUBLE (15,5) DEFAULT 0,
`ACCUMULATEDQTY` DOUBLE (15,5) DEFAULT 0,
`ACCUMULATEDCOST` DOUBLE (15,5) DEFAULT 0,
PRIMARY KEY(`M_PRODUCT_ID`)
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`M_UOM_CONVERSION` (
`M_UOM_CONVERSION_ID` INT( 10 ) NOT NULL ,
`M_BASE_UOM_ID` INT( 10 ) NOT NULL ,
`M_DRIVED_UOM_ID` INT( 10 ) NOT NULL ,
`M_PRODUCT_ID` INT(10) NOT NULL,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`MULTIPLIER` DOUBLE (15,5) DEFAULT 0,
PRIMARY KEY ( `M_UOM_CONVERSION_ID` ),
UNIQUE KEY (`M_BASE_UOM_ID`,`M_DRIVED_UOM_ID`,`M_PRODUCT_ID`)
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`M_BPARTNER` (
`M_BPARTNER_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`NAME` VARCHAR( 60 ) NOT NULL ,
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`ISVENDOR` CHAR( 1 ) NOT NULL DEFAULT 'N',
`ISCUSTOMER` CHAR( 1 ) NOT NULL DEFAULT 'Y',
PRIMARY KEY ( `M_BPARTNER_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`M_SHOP` (
`M_SHOP_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`NAME` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
PRIMARY KEY ( `M_SHOP_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`M_WAREHOUSE` (
`M_WAREHOUSE_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`NAME` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
PRIMARY KEY ( `M_WAREHOUSE_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`U_USER` (
`U_USER_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`FIRSTNAME` VARCHAR( 60 ) NOT NULL ,
`MIDDLENAME` VARCHAR( 60 ) NOT NULL ,
`LASTNAME` VARCHAR( 60 ) NOT NULL ,
`USERNAME` VARCHAR( 60 ) NOT NULL ,
`PASSWORD` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
UNIQUE (`USERNAME`),
PRIMARY KEY ( `U_USER_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`U_SEQUENCE` (
`U_SEQUENCE_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`NAME` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`ISTABLEID` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`BASEDOC` VARCHAR( 10 ) NOT NULL,
`CURRENTNEXT` INT( 10 ) NULL ,
PRIMARY KEY ( `U_SEQUENCE_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`U_WAREHOUSEACCESS` (
`M_SHOP_ID` INT( 10 ) NOT NULL ,
`U_USER_ID` INT( 10 ) NOT NULL ,
`M_WAREHOUSE_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`CANSALEFROM` CHAR( 1 ) NOT NULL DEFAULT 'N',
`CANBUYFOR` CHAR( 1 ) NOT NULL DEFAULT 'N',
`CANMOVEFORM` CHAR( 1 ) NOT NULL DEFAULT 'N',
`CANMOVETO` CHAR( 1 ) NOT NULL DEFAULT 'N',
`CANUSEFROM` CHAR( 1 ) NOT NULL DEFAULT 'N',
`CANCOUNT` CHAR( 1 ) NOT NULL DEFAULT 'N',
PRIMARY KEY ( `M_SHOP_ID`,`U_USER_ID`,`M_WAREHOUSE_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`U_FORMACCESS` (
`M_SHOP_ID` INT( 10 ) NOT NULL ,
`U_USER_ID` INT( 10 ) NOT NULL ,
`FORMNAME` VARCHAR( 30 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`ACCESSLEVEL` VARCHAR(20) NOT NULL DEFAULT 'NA',
PRIMARY KEY ( `M_SHOP_ID`,`U_USER_ID`,`FORMNAME` )
) ENGINE = MYISAM ;


CREATE TABLE `SRPDB`.`U_SHOPACCESS` (
`M_SHOP_ID` INT( 10 ) NOT NULL ,
`U_USER_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`ACCESSLEVEL` VARCHAR(20) NOT NULL DEFAULT 'NA',
PRIMARY KEY ( `M_SHOP_ID`,`U_USER_ID`)
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`U_ACTIVESHOPID` (
`M_SHOP_ID` INT( 10 ) NOT NULL,
PRIMARY KEY (`M_SHOP_ID`)
) ENGINE = MYISAM ;

INSERT INTO `srpdb`.`u_activeshopid` (
`M_SHOP_ID`
)
VALUES (
'1000'
);


CREATE TABLE `SRPDB`.`T_TRANSACTION`(
`T_TRANSACTION_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`DOCUMENTNO` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`TRXDATE` DATETIME NOT NULL ,
`M_BPARTNER_ID` INT( 10 ) NOT NULL ,
`ISSALESTRX` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`SUBTRXAMOUNT` DOUBLE (15,2),
`GRANDTRXAMOUNT` DOUBLE (15,2),
`TRXTAXAMOUNT` DOUBLE (15,2),
`ISPAID` CHAR (1) NOT NULL DEFAULT 'Y',
`PAYMENTRULE` CHAR (1) NOT NULL DEFAULT 'P',
`DOCSTATUS` CHAR ( 2 ) NOT NULL DEFAULT 'DR',
`PROCESSED` CHAR ( 1 ) NOT NULL DEFAULT 'N',
PRIMARY KEY ( `T_TRANSACTION_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`T_TRXDETAIL`(
`T_TRXDETAIL_ID` INT( 10 ) NOT NULL ,
`T_TRANSACTION_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`TRXDATE` DATETIME NOT NULL ,
`M_BPARTNER_ID` INT( 10 ) NOT NULL ,
`ISSALESTRX` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`M_PRODUCT_ID` INT(10) NOT NULL,
`M_UOM_ID` INT( 10 ) NOT NULL ,
`M_WAREHOUSE_ID` INT( 10 ) NOT NULL ,
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`TRXQUANTITY` DOUBLE (15,5) NOT NULL,
`UNITPRICE` DOUBLE (15,2) DEFAULT 0,
`DISCOUNTRATE` DOUBLE (15,5) DEFAULT 0,
`DISCOUNTAMT` DOUBLE (15,2) DEFAULT 0,
`MARGIN` DOUBLE (15,5) DEFAULT 0,
`UNITCOST` DOUBLE (15,5) DEFAULT 0,
`LINENETAMT` DOUBLE (15,2) DEFAULT 0,
`LINETAXAMOUNT` DOUBLE (15,2) DEFAULT 0,
PRIMARY KEY ( `T_TRXDETAIL_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`T_MOVEMENT`(
`T_MOVEMENT_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`DOCUMENTNO` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`MOVEDATE` DATETIME NOT NULL ,
`M_WAREHOUSEFROM_ID` INT( 10 ) NOT NULL ,
`M_WAREHOUSETO_ID` INT( 10 ) NOT NULL ,
`DOCSTATUS` CHAR ( 2 ) NOT NULL DEFAULT 'DR',
`PROCESSED` CHAR ( 1 ) NOT NULL DEFAULT 'N',
PRIMARY KEY ( `T_MOVEMENT_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`T_MOVEMENTDETAIL`(
`T_MOVEMENTDETAIL_ID` INT( 10 ) NOT NULL ,
`T_MOVEMENT_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`MOVEDATE` DATETIME NOT NULL ,
`M_WAREHOUSEFROM_ID` INT( 10 ) NOT NULL ,
`M_WAREHOUSETO_ID` INT( 10 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`M_PRODUCT_ID` INT(10) NOT NULL,
`M_UOM_ID` INT( 10 ) NOT NULL ,
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`MOVEQUANTITY` DOUBLE (15,5) NOT NULL,
PRIMARY KEY ( `T_MOVEMENTDETAIL_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`Q_COST`(
`M_PRODUCT_ID` INT(10) NOT NULL,
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`CURRENTQTY` DOUBLE (15,5),
`CURRENTCOST` DOUBLE (15,5),
`ACCUMULATEDQTY` DOUBLE (15,5),
`ACCUMULATEDCOST` DOUBLE (15,5),
PRIMARY KEY ( `M_PRODUCT_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`Q_STOCK`(
`M_PRODUCT_ID` INT(10) NOT NULL,
`M_WAREHOUSE_ID` INT(10) NOT NULL,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`CREATED` DATETIME NOT NULL ,
`CREATEDBY` INT( 10 ) NOT NULL,
`UPDATED` DATETIME NOT NULL ,
`UPDATEDBY` INT( 10 ) NOT NULL,
`CURRENTQTY` DOUBLE (15,5),
PRIMARY KEY ( `M_PRODUCT_ID`,`M_WAREHOUSE_ID` )
) ENGINE = MYISAM ;


INSERT INTO `srpdb`.`u_sequence` (`U_SEQUENCE_ID` ,`CREATED` ,`UPDATED` ,`NAME` ,`ISACTIVE` ,`ISTABLEID` ,`BASEDOC` ,`CURRENTNEXT`)
VALUES ('1000', NOW( ) , NOW( ), 'U_SEQUENCE', 'Y','Y','', '1016'),
	   ('1001', NOW( ) , NOW( ), 'M_CITY', 'Y','Y','','1000'),
	   ('1002', NOW( ) , NOW( ), 'M_LOCALITY', 'Y','Y','','1000'),
	   ('1003', NOW( ) , NOW( ), 'M_SUBLOCALITY', 'Y','Y','','1000'),
	   ('1004', NOW( ) , NOW( ), 'M_UOM', 'Y','Y','','1000'),
	   ('1005', NOW( ) , NOW( ), 'M_PRODUCTCATEGORY', 'Y','Y','','1000'),
	   ('1006', NOW( ) , NOW( ), 'M_PRODUCT', 'Y','Y','','1000'),
	   ('1007', NOW( ) , NOW( ), 'M_BPARTNER', 'Y','Y','','1000'),
	   ('1008', NOW( ) , NOW( ), 'M_SHOP', 'Y','Y','','1000'),
	   ('1009', NOW( ) , NOW( ), 'U_USER', 'Y','Y','','1000'),
	   ('1010', NOW( ) , NOW( ), 'T_TRANSACTION', 'Y','Y','','1000'),
	   ('1011', NOW( ) , NOW( ), 'T_TRXDETAIL', 'Y','Y','','1000'),
	   ('1012', NOW( ) , NOW( ), 'M_UOM_CONVERSION', 'Y','Y','','1000'),
	   ('1013', NOW( ) , NOW( ) , 'PURCHASE', 'Y', 'N', 'PURCHASE', '1'), 
	   ('1014', NOW( ) , NOW( ) , 'SALES', 'Y', 'N', 'SALES', '1'),
	   ('1015', NOW( ) , NOW( ) , 'M_WAREHOUSE', 'Y', 'Y', '', '1000'),
	   ('1016', NOW( ) , NOW( ) , 'T_MOVEMENT', 'Y', 'Y', '', '1000'),
	   ('1017', NOW( ) , NOW( ) , 'T_MOVEMENTDETAIL', 'Y', 'Y', '', '1000'),
	   ('1018', NOW( ) , NOW( ) , 'MOVE', 'Y', 'N', 'MOVE', '1'),
	   ('1019', NOW( ) , NOW( ) , 'USE', 'Y', 'N', 'USE', '1'),
	   ('1020', NOW( ) , NOW( ) , 'COUNT', 'Y', 'N', 'COUNT', '1'),	   
	   ('1021', NOW( ) , NOW( ) , 'T_PHYSICALCOUNT', 'Y', 'Y', '', '1000'),
	   ('1022', NOW( ) , NOW( ) , 'T_PHYSICALCOUNTDETAIL', 'Y', 'Y', '', '1000'),
	   ('1023', NOW( ) , NOW( ) , 'T_INVENTORYUSE', 'Y', 'Y', '', '1000'),
	   ('1024', NOW( ) , NOW( ) , 'T_INVENTORYUSEDETAIL', 'Y', 'Y', '', '1000');


