CREATE DATABASE `SRPDB` DEFAULT CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI;

CREATE TABLE `SRPDB`.`M_CITY` (
`M_CITY_ID` INT( 10 ) NOT NULL ,
`NAME` VARCHAR( 60 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`UPDATED` DATETIME NOT NULL ,
`COUNTRY` VARCHAR( 60 ) NOT NULL ,
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
PRIMARY KEY ( `M_CITY_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`M_LOCALITY` (
`M_LOCALITY_ID` INT( 10 ) NOT NULL ,
`M_CITY_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`UPDATED` DATETIME NOT NULL ,
`NAME` VARCHAR( 60 ) NOT NULL ,
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`ISSUMMARY` CHAR( 1 ) NOT NULL DEFAULT 'N',
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`M_PARENTLOCALITY_ID` INT NOT NULL ,
PRIMARY KEY ( `M_LOCALITY_ID` )
) ENGINE = MYISAM ;


CREATE TABLE `SRPDB`.`M_SUBLOCALITY` (
`M_SUBLOCALITY_ID` INT( 10 ) NOT NULL ,
`M_LOCALITY_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`UPDATED` DATETIME NOT NULL ,
`NAME` VARCHAR( 60 ) NOT NULL ,
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`ISSUMMARY` CHAR( 1 ) NOT NULL DEFAULT 'N',
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`M_PARENTSUBLOC_ID` INT NOT NULL ,
PRIMARY KEY ( `M_SUBLOCALITY_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`M_UOM` (
`M_UOM_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`UPDATED` DATETIME NOT NULL ,
`NAME` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`STDPRECISION` INT( 1 ) NOT NULL DEFAULT '0',
`ABBREVATION` CHAR( 3 ) NOT NULL ,
`DESCRIPTION` VARCHAR( 255 ) NULL ,
PRIMARY KEY ( `M_UOM_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`M_PRODUCTCATEGORY` (
`M_PRODUCTCATEGORY_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`UPDATED` DATETIME NOT NULL ,
`NAME` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
PRIMARY KEY ( `M_PRODUCTCATEGORY_ID` )
) ENGINE = MYISAM ;


CREATE TABLE `SRPDB`.`M_PRODUCT`(
`M_PRODUCT_ID` INT(10) NOT NULL,
`CREATED` DATETIME NOT NULL ,
`UPDATED` DATETIME NOT NULL ,
`CODE` VARCHAR( 60 ) NOT NULL ,
`NAME` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`M_PRODUCTCATEGORY_ID` INT( 10 ) NOT NULL ,
`M_UOM_ID` INT( 10 ) NOT NULL ,
`PRODUCTTYPE` CHAR(1) NOT NULL,
`UPC_EAN` VARCHAR( 255 ) NULL ,
`IMAGEPATH` VARCHAR( 255 ) NULL ,
`PURCHASEPRICE` DOUBLE (15,5) DEFAULT 0,
`SELLINGPRICE` DOUBLE (15,5) DEFAULT 0,
`CURRENTQTY` DOUBLE (15,5) DEFAULT 0,
`CURRENTCOST` DOUBLE (15,5) DEFAULT 0,
`ACCUMULATEDQTY` DOUBLE (15,5) DEFAULT 0,
`ACCUMULATEDCOST` DOUBLE (15,5) DEFAULT 0,
PRIMARY KEY(`M_PRODUCT_ID`)
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`M_UOM_CONVERSION` (
`M_UOM_CONVERSION_ID` INT( 10 ) NOT NULL ,
`M_BASE_UOM_ID` INT( 10 ) NOT NULL ,
`M_DRIVED_UOM_ID` INT( 10 ) NOT NULL ,
`M_PRODUCT_ID` INT(10) NOT NULL,
`CREATED` DATETIME NOT NULL ,
`UPDATED` DATETIME NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`MULTIPLIER` DOUBLE (15,5) DEFAULT 0,
PRIMARY KEY ( `M_UOM_CONVERSION_ID` ),
UNIQUE KEY (`M_BASE_UOM_ID`,`M_DRIVED_UOM_ID`,`M_PRODUCT_ID`)
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`M_BPARTNER` (
`M_BPARTNER_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`UPDATED` DATETIME NOT NULL ,
`NAME` VARCHAR( 60 ) NOT NULL ,
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`ISVENDOR` CHAR( 1 ) NOT NULL DEFAULT 'N',
`ISCUSTOMER` CHAR( 1 ) NOT NULL DEFAULT 'Y',
PRIMARY KEY ( `M_BPARTNER_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`M_SHOP` (
`M_SHOP_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`UPDATED` DATETIME NOT NULL ,
`NAME` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
PRIMARY KEY ( `M_SHOP_ID` )
) ENGINE = MYISAM ;


CREATE TABLE `SRPDB`.`M_WAREHOUSE` (
`M_WAREHOUSE_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`UPDATED` DATETIME NOT NULL ,
`NAME` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
PRIMARY KEY ( `M_SHOP_ID` )
) ENGINE = MYISAM ;


CREATE TABLE `SRPDB`.`U_USER` (
`U_USER_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`UPDATED` DATETIME NOT NULL ,
`FIRSTNAME` VARCHAR( 60 ) NOT NULL ,
`MIDDLENAME` VARCHAR( 60 ) NOT NULL ,
`LASTNAME` VARCHAR( 60 ) NOT NULL ,
`USERNAME` VARCHAR( 60 ) NOT NULL ,
`PASSWORD` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
PRIMARY KEY ( `U_USER_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`U_SEQUENCE` (
`U_SEQUENCE_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`UPDATED` DATETIME NOT NULL ,
`NAME` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`CURRENTNEXT` INT( 10 ) NULL ,
PRIMARY KEY ( `U_SEQUENCE_ID` )
) ENGINE = MYISAM ;


CREATE TABLE `SRPDB`.`T_TRANSACTION`(
`T_TRANSACTION_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`UPDATED` DATETIME NOT NULL ,
`DOCUMENTNO` VARCHAR( 60 ) NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`TRXDATE` DATETIME NOT NULL ,
`M_BPARTNER_ID` INT( 10 ) NOT NULL ,
`ISSALESTRX` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`SUBTRXAMOUNT` DOUBLE (15,2),
`GRANDTRXAMOUNT` DOUBLE (15,2),
`TRXTAXAMOUNT` DOUBLE (15,2),
`DOCSTATUS` CHAR ( 2 ) NOT NULL DEFAULT 'DR',
`PROCESSED` CHAR ( 1 ) NOT NULL DEFAULT 'N',
PRIMARY KEY ( `T_TRANSACTION_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`T_TRXDETAIL`(
`T_TRXDETAIL_ID` INT( 10 ) NOT NULL ,
`T_TRANSACTION_ID` INT( 10 ) NOT NULL ,
`CREATED` DATETIME NOT NULL ,
`UPDATED` DATETIME NOT NULL ,
`TRXDATE` DATETIME NOT NULL ,
`M_BPARTNER_ID` INT( 10 ) NOT NULL ,
`ISSALESTRX` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`M_PRODUCT_ID` INT(10) NOT NULL,
`M_UOM_ID` INT( 10 ) NOT NULL ,
`DESCRIPTION` VARCHAR( 255 ) NULL ,
`TRXQUANTITY` DOUBLE (15,5) NOT NULL,
`UNITPRICE` DOUBLE (15,2) DEFAULT 0,
`DISCOUNTRATE` DOUBLE (15,5) DEFAULT 0,
`DISCOUNTAMT` DOUBLE (15,2) DEFAULT 0,
`LINENETAMT` DOUBLE (15,2) DEFAULT 0,
`LINETAXAMOUNT` DOUBLE (15,2) DEFAULT 0,
PRIMARY KEY ( `T_TRXDETAIL_ID` )
) ENGINE = MYISAM ;


CREATE TABLE `SRPDB`.`Q_COST`(
`M_PRODUCT_ID` INT(10) NOT NULL,
`CREATED` DATETIME NOT NULL ,
`UPDATED` DATETIME NOT NULL ,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`CURRENTQTY` DOUBLE (15,5),
`CURRENTCOST` DOUBLE (15,5),
`ACCUMULATEDQTY` DOUBLE (15,5),
`ACCUMULATEDCOST` DOUBLE (15,5),
PRIMARY KEY ( `M_PRODUCT_ID` )
) ENGINE = MYISAM ;

CREATE TABLE `SRPDB`.`Q_STOCK`(
`M_PRODUCT_ID` INT(10) NOT NULL,
`ISACTIVE` CHAR( 1 ) NOT NULL DEFAULT 'Y',
`CREATED` DATETIME NOT NULL ,
`UPDATED` DATETIME NOT NULL ,
`CURRENTQTY` DOUBLE (15,5),
PRIMARY KEY ( `M_PRODUCT_ID` )
) ENGINE = MYISAM ;


INSERT INTO `srpdb`.`u_sequence` (`U_SEQUENCE_ID` ,`CREATED` ,`UPDATED` ,`NAME` ,`ISACTIVE` ,`CURRENTNEXT`)
VALUES ('1000', '2011-01-30 12:45:08', '2011-01-30 12:45:24', 'U_SEQUENCE', 'Y', '1013');

INSERT INTO `srpdb`.`u_sequence` (`U_SEQUENCE_ID` ,`CREATED` ,`UPDATED` ,`NAME` ,`ISACTIVE` ,`CURRENTNEXT`)
VALUES ('1001', '2011-01-30 12:45:08', '2011-01-30 12:45:24', 'M_CITY', 'Y', '1000');

INSERT INTO `srpdb`.`u_sequence` (`U_SEQUENCE_ID` ,`CREATED` ,`UPDATED` ,`NAME` ,`ISACTIVE` ,`CURRENTNEXT`)
VALUES ('1002', '2011-01-30 12:45:08', '2011-01-30 12:45:24', 'M_LOCALITY', 'Y', '1000');

INSERT INTO `srpdb`.`u_sequence` (`U_SEQUENCE_ID` ,`CREATED` ,`UPDATED` ,`NAME` ,`ISACTIVE` ,`CURRENTNEXT`)
VALUES ('1003', '2011-01-30 12:45:08', '2011-01-30 12:45:24', 'M_SUBLOCALITY', 'Y', '1000');

INSERT INTO `srpdb`.`u_sequence` (`U_SEQUENCE_ID` ,`CREATED` ,`UPDATED` ,`NAME` ,`ISACTIVE` ,`CURRENTNEXT`)
VALUES ('1004', '2011-01-30 12:45:08', '2011-01-30 12:45:24', 'M_UOM', 'Y', '1000');

INSERT INTO `srpdb`.`u_sequence` (`U_SEQUENCE_ID` ,`CREATED` ,`UPDATED` ,`NAME` ,`ISACTIVE` ,`CURRENTNEXT`)
VALUES ('1005', '2011-01-30 12:45:08', '2011-01-30 12:45:24', 'M_PRODUCTCATEGORY', 'Y', '1000');

INSERT INTO `srpdb`.`u_sequence` (`U_SEQUENCE_ID` ,`CREATED` ,`UPDATED` ,`NAME` ,`ISACTIVE` ,`CURRENTNEXT`)
VALUES ('1006', '2011-01-30 12:45:08', '2011-01-30 12:45:24', 'M_PRODUCT', 'Y', '1000');

INSERT INTO `srpdb`.`u_sequence` (`U_SEQUENCE_ID` ,`CREATED` ,`UPDATED` ,`NAME` ,`ISACTIVE` ,`CURRENTNEXT`)
VALUES ('1012', '2011-01-30 12:45:08', '2011-01-30 12:45:24', 'M_UOM_CONVERSION', 'Y', '1000');

INSERT INTO `srpdb`.`u_sequence` (`U_SEQUENCE_ID` ,`CREATED` ,`UPDATED` ,`NAME` ,`ISACTIVE` ,`CURRENTNEXT`)
VALUES ('1007', '2011-01-30 12:45:08', '2011-01-30 12:45:24', 'M_BPARTNER', 'Y', '1000');

INSERT INTO `srpdb`.`u_sequence` (`U_SEQUENCE_ID` ,`CREATED` ,`UPDATED` ,`NAME` ,`ISACTIVE` ,`CURRENTNEXT`)
VALUES ('1008', '2011-01-30 12:45:08', '2011-01-30 12:45:24', 'M_SHOP', 'Y', '1000');

M_WAREHOUSE

INSERT INTO `srpdb`.`u_sequence` (`U_SEQUENCE_ID` ,`CREATED` ,`UPDATED` ,`NAME` ,`ISACTIVE` ,`CURRENTNEXT`)
VALUES ('1009', '2011-01-30 12:45:08', '2011-01-30 12:45:24', 'U_USER', 'Y', '1000');

INSERT INTO `srpdb`.`u_sequence` (`U_SEQUENCE_ID` ,`CREATED` ,`UPDATED` ,`NAME` ,`ISACTIVE` ,`CURRENTNEXT`)
VALUES ('1010', '2011-01-30 12:45:08', '2011-01-30 12:45:24', 'T_TRANSACTION', 'Y', '1000');

INSERT INTO `srpdb`.`u_sequence` (`U_SEQUENCE_ID` ,`CREATED` ,`UPDATED` ,`NAME` ,`ISACTIVE` ,`CURRENTNEXT`)
VALUES ('1011', '2011-01-30 12:45:08', '2011-01-30 12:45:24', 'T_TRXDETAIL', 'Y', '1000');

