CREATE VIEW `V_TRXDETAIL` AS
SELECT 
	ORDER.T_TRANSACTION_ID AS T_TRANSACTION_ID,
	ORDER.M_SHOP_ID AS M_SHOP_ID,
	ORDER.DOCUMENTNO AS DOCUMENTNO,
	ORDER.TRXDATE AS TRXDATE,
	ORDER.M_BPARTNER_ID AS M_BPARTNER_ID,
	ORDER.ISSALESTRX AS ISSALESTRX,
	ORDER.SUBTRXAMOUNT AS SUBTRXAMOUNT,
	ORDER.GRANDTRXAMOUNT AS GRANDTRXAMOUNT,
	ORDER.TRXTAXAMOUNT AS TRXTAXAMOUNT,
	ORDER.ISPAID AS ISPAID,
	ORDER.PAYMENTRULE AS PAYMENTRULE,
	ORDER.DOCSTATUS AS DOCSTATUS,
	ORDER.PROCESSED AS PROCESSED,
	ORDERLINE.T_TRXDETAIL_ID AS T_TRXDETAIL_ID,
	ORDERLINE.LINE AS LINE,
	ORDERLINE.M_PRODUCT_ID AS M_PRODUCT_ID,
	ORDERLINE.M_UOM_ID AS M_UOM_ID,
	ORDERLINE.M_WAREHOUSE_ID AS M_WAREHOUSE_ID,
	ORDERLINE.TRXQUANTITY AS TRXQUANTITY,
	ORDERLINE.UNITPRICE AS UNITPRICE,
	ORDERLINE.DISCOUNTRATE AS DISCOUNTRATE,
	ORDERLINE.DISCOUNTAMT AS DISCOUNTAMT,
	ORDERLINE.MARGIN AS MARGIN,
	ORDERLINE.UNITCOST AS UNITCOST,
	ORDERLINE.LINENETAMT AS LINENETAMT,
	ORDERLINE.LINETAXAMOUNT AS LINETAXAMOUNT,
	PRD.CODE AS CODE,
	PRD.NAME AS PRODUCT,
	PRD.M_PRODUCTCATEGORY_ID AS M_PRODUCTCATEGORY_ID,
	PRD_CAT.NAME AS CATEGORY,
	UOM.NAME AS UNIT,
	UOM.ABBREVATION AS UOM,
	BPRTNER.NAME AS BUSINESSPARTNER,
	STATION.NAME AS STATION,
	WAREHOUSE.NAME AS NAME
FROM ((((((`T_TRANSACTION` `ORDER` LEFT JOIN `T_TRXDETAIL` `ORDERLINE`
ON `ORDER`.`T_TRANSACTION_ID` = `ORDERLINE`.`T_TRANSACTION_ID`) 
LEFT JOIN `M_PRODUCT` `PRD`
ON `ORDERLINE`.`M_PRODUCT_ID` = `PRD`.`M_PRODUCT_ID`)
LEFT JOIN `M_PRODUCTCATEGORY` `PRD_CAT`
ON `PRD`.`M_PRODUCTCATEGORY_ID` = `PRD_CAT`.`M_PRODUCTCATEGORY_ID`)
LEFT JOIN `M_UOM` `UOM`
ON `ORDERLINE`.`M_UOM_ID` = `UOM`.`M_UOM_ID`)
LEFT JOIN `M_BPARTNER` `BPRTNER`
ON `ORDER`.`M_BPARTNER_ID` = `BPRTNER`.`M_BPARTNER_ID`)
LEFT JOIN `M_SHOP` `STATION`
ON `ORDER`.`M_SHOP_ID` = `STATION`.`M_SHOP_ID`)
LEFT JOIN `M_WAREHOUSE` `WAREHOUSE`
ON `ORDERLINE`.`M_WAREHOUSE_ID` = `WAREHOUSE`.`M_WAREHOUSE_ID`