using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;

namespace SRP
{

    enum triStateBool
    { yes,
        No,
        ignor }

    enum transactionType
    { None,InventoryOut, InventoryIn, Move, Count, Use , report}

    enum transactionStatus
    { ignor ,Draft, Complete, Reversed }

    enum accessLevel
    { ignor, InActive, ReadWite,ReadOnly  }

    enum reportLevel
    { None, Summary, Detail}

    enum reportType
    { None, InventoryIn, InventoryOut, 
        InventoryMove, InventoryCount, 
        InventoryUse, TransactionSummary,
        InventoryQuantity}

    enum movementType
    { BL, V_p, V_n, M_p, M_n, I_p, I_n, C_p, C_n }

    class dbSettingInformationHandler
    {
        public static string settingFilePath = "settings.xml";
        public static bool documentNumberAutoGenerated = false;
        
        public static string SRPDataBaseType = "MySql";
        public static string SRPHostName = "";
        public static string SRPDataBaseName = "";
        public static string SRPDBUserName = "";
        public static string SRPDBPassword = "";
        public static string SRPScriptDirectory = "";
        public static string SRPWarningDirectory = "";
        public static string SRPErrorDirectory = "";
        public static string SRPDBPort = "";
        public static string SRPPrinerName = "";
        public static bool SRPLogChangeScript = false;
        public static int SRPSyncTimeInterval = 0;
        public static int SRPToCompiereWarning = 0;
        public static int SRPToCompiereError = 0;

    }

    class generalResultInformation
    {
        public static string stNewCustomerId = "";
        public static transactionType currentTrx = transactionType.None;
        public static reportLevel currentRequestedRptLevel = reportLevel.None;
        public static reportType currentRequestedRptType = reportType.None;
        public static string selectedProductId = "";

        public static string clientId = "1000000";
        public static string organiztionId = "";
        public static string Station = "";
        public static string userId = "";
        public static string userName = "";

        public static bool logedIn = false;
        
        public static int userLoginTrials = 5;
        public static int dbConfigTrials = 3;
        public static int dbBulkDataRetrivalSize = 50;

        public static string activeStation = "0";

        public static string documentBaseType = "MMM";        
        public static string allOrganisationRepresentativeKey = "0";
        public static string allStationRepresentativeKey = "0";
        public static string allWarehouseRepresentativeKey = "0";

        public static DataTable searchResult = new DataTable();
        public static DataTable searchCritrion = new DataTable();
        public static string logicConnector = "";
        public static bool isRequest = false;

        public static string[] formNameList = new string[]{};
        public static string[] hiddenFormNameList = new string[] { };
        public static bool currentFormIsReadOnly = false;
    }
        
    class unitConvesionInformation
    {
        public static string stBaseProductId = "";
        public static string stBaseUnitId = "";
        public static string stDrivedUnitId = ""; 
    }

    class shortTransactionInformation
    {
        public static string stNewCustomerId = "";
        public static string stProductId = "";
        public static transactionType ttTransactionType = transactionType.None;
        public static bool transactionConducted = false;
    }

    class attachmentInformation 
    {
        public static string stTransactionId = "";
    }

    class dbCommitFailure
    {
        public static bool dbCommitError = false;
        public static bool dbCommitWarnning = false;

        public static string dbCommitErrorMessage = "";
        public static string dbCommitWarnningMessage = "";

    }

    class currentFrmoperationPrivilages
    {
        public static bool canCreateNew = false;
        public static bool canSave = false;
        public static bool canSearch = false;
        public static bool canNavigate = false;
        public static bool canDelete = false;
        public static bool canReverse = false;
        public static bool canConfirm = false;
        public static bool canPrint = false;
    }

    class frmAccessPrivilages
    {
        //Record
        public static accessLevel accFrmUsers = accessLevel.InActive;
        public static accessLevel accFrmStations = accessLevel.InActive;
        public static accessLevel accFrmOrganisation = accessLevel.InActive;
        public static accessLevel accFrmCitiesAndLocalites = accessLevel.InActive;
        public static accessLevel accFrmBpartner = accessLevel.InActive;
        public static accessLevel accFrmUOM = accessLevel.InActive;
        public static accessLevel accFrmUOMConversion = accessLevel.InActive;
        public static accessLevel accFrmPrdCategory = accessLevel.InActive;
        public static accessLevel accFrmProduct = accessLevel.InActive;
        public static accessLevel accFrmWareHouse = accessLevel.InActive;

        //Conduct
        public static accessLevel accFrmInventoryIn = accessLevel.InActive;
        public static accessLevel accFrmInventoryOut = accessLevel.InActive;
        public static accessLevel accFrmInventoryMove = accessLevel.InActive;
        public static accessLevel accFrmPhysicalInventory = accessLevel.InActive;
        public static accessLevel accFrmInventoryUse = accessLevel.InActive;

        //Utilities
        public static accessLevel accFrmMergeEntity = accessLevel.InActive;
        public static accessLevel accFrmCleanStorage = accessLevel.InActive;
        public static accessLevel accFrmStationAccess = accessLevel.InActive;
        public static accessLevel accFrmOrganisationAccess = accessLevel.InActive;
        public static accessLevel accFrmFormAccess = accessLevel.InActive;
        public static accessLevel accFrmOperationAccess = accessLevel.InActive;
        public static accessLevel accFrmWareHouseAccess = accessLevel.InActive;
        public static accessLevel accFrmClearLog = accessLevel.InActive;
        public static accessLevel accFrmChangeTheme = accessLevel.InActive;

    }
}
