namespace POSDocumentPrinter
{
    partial class frmsettings
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmsettings));
            this.grbDataBaseSettings = new System.Windows.Forms.GroupBox();
            this.ControlAttachmentPrint = new System.Windows.Forms.CheckBox();
            this.AutoGenerateDeliveryOrder = new System.Windows.Forms.CheckBox();
            this.ControlDepositSourceConsistency = new System.Windows.Forms.CheckBox();
            this.PrinterName = new System.Windows.Forms.ComboBox();
            this.DataBaseType = new System.Windows.Forms.ComboBox();
            this.lblDataBaseType = new System.Windows.Forms.Label();
            this.AllowDeliveryOrderPrinting = new System.Windows.Forms.CheckBox();
            this.AutoGenerateDocumentNumber = new System.Windows.Forms.CheckBox();
            this.allowNegativeStock = new System.Windows.Forms.CheckBox();
            this.LogChangeScripts = new System.Windows.Forms.CheckBox();
            this.cmdEasyMoveWarningFolder = new System.Windows.Forms.Button();
            this.DBPort = new System.Windows.Forms.TextBox();
            this.cmdEasyMoveScriptFolder = new System.Windows.Forms.Button();
            this.cmdEasyMoveErrFolder = new System.Windows.Forms.Button();
            this.lblDBPort = new System.Windows.Forms.Label();
            this.cmdSettingSave = new System.Windows.Forms.Button();
            this.cmdSettingTest = new System.Windows.Forms.Button();
            this.WarningDir = new System.Windows.Forms.TextBox();
            this.ErrorDir = new System.Windows.Forms.TextBox();
            this.DBPassword = new System.Windows.Forms.TextBox();
            this.DBUserName = new System.Windows.Forms.TextBox();
            this.DataBaseName = new System.Windows.Forms.TextBox();
            this.MRCnumber = new System.Windows.Forms.TextBox();
            this.centralNode = new System.Windows.Forms.TextBox();
            this.Node = new System.Windows.Forms.TextBox();
            this.Station = new System.Windows.Forms.TextBox();
            this.DBServerName = new System.Windows.Forms.TextBox();
            this.ScriptDir = new System.Windows.Forms.TextBox();
            this.lblPrinterName = new System.Windows.Forms.Label();
            this.lblWarningDir = new System.Windows.Forms.Label();
            this.lblErrorDir = new System.Windows.Forms.Label();
            this.lblMRCnumber = new System.Windows.Forms.Label();
            this.lblScriptDir = new System.Windows.Forms.Label();
            this.lblcentralNode = new System.Windows.Forms.Label();
            this.lblDBPassword = new System.Windows.Forms.Label();
            this.lblNode = new System.Windows.Forms.Label();
            this.lblDBUserName = new System.Windows.Forms.Label();
            this.lblStation = new System.Windows.Forms.Label();
            this.lblDataBaseName = new System.Windows.Forms.Label();
            this.lblDBServerName = new System.Windows.Forms.Label();
            this.folderBrowserDialog1 = new System.Windows.Forms.FolderBrowserDialog();
            this.LDAPAuthenticated = new System.Windows.Forms.CheckBox();
            this.grbDataBaseSettings.SuspendLayout();
            this.SuspendLayout();
            // 
            // grbDataBaseSettings
            // 
            this.grbDataBaseSettings.Controls.Add(this.LDAPAuthenticated);
            this.grbDataBaseSettings.Controls.Add(this.ControlAttachmentPrint);
            this.grbDataBaseSettings.Controls.Add(this.AutoGenerateDeliveryOrder);
            this.grbDataBaseSettings.Controls.Add(this.ControlDepositSourceConsistency);
            this.grbDataBaseSettings.Controls.Add(this.PrinterName);
            this.grbDataBaseSettings.Controls.Add(this.DataBaseType);
            this.grbDataBaseSettings.Controls.Add(this.lblDataBaseType);
            this.grbDataBaseSettings.Controls.Add(this.AllowDeliveryOrderPrinting);
            this.grbDataBaseSettings.Controls.Add(this.AutoGenerateDocumentNumber);
            this.grbDataBaseSettings.Controls.Add(this.allowNegativeStock);
            this.grbDataBaseSettings.Controls.Add(this.LogChangeScripts);
            this.grbDataBaseSettings.Controls.Add(this.cmdEasyMoveWarningFolder);
            this.grbDataBaseSettings.Controls.Add(this.DBPort);
            this.grbDataBaseSettings.Controls.Add(this.cmdEasyMoveScriptFolder);
            this.grbDataBaseSettings.Controls.Add(this.cmdEasyMoveErrFolder);
            this.grbDataBaseSettings.Controls.Add(this.lblDBPort);
            this.grbDataBaseSettings.Controls.Add(this.cmdSettingSave);
            this.grbDataBaseSettings.Controls.Add(this.cmdSettingTest);
            this.grbDataBaseSettings.Controls.Add(this.WarningDir);
            this.grbDataBaseSettings.Controls.Add(this.ErrorDir);
            this.grbDataBaseSettings.Controls.Add(this.DBPassword);
            this.grbDataBaseSettings.Controls.Add(this.DBUserName);
            this.grbDataBaseSettings.Controls.Add(this.DataBaseName);
            this.grbDataBaseSettings.Controls.Add(this.MRCnumber);
            this.grbDataBaseSettings.Controls.Add(this.centralNode);
            this.grbDataBaseSettings.Controls.Add(this.Node);
            this.grbDataBaseSettings.Controls.Add(this.Station);
            this.grbDataBaseSettings.Controls.Add(this.DBServerName);
            this.grbDataBaseSettings.Controls.Add(this.ScriptDir);
            this.grbDataBaseSettings.Controls.Add(this.lblPrinterName);
            this.grbDataBaseSettings.Controls.Add(this.lblWarningDir);
            this.grbDataBaseSettings.Controls.Add(this.lblErrorDir);
            this.grbDataBaseSettings.Controls.Add(this.lblMRCnumber);
            this.grbDataBaseSettings.Controls.Add(this.lblScriptDir);
            this.grbDataBaseSettings.Controls.Add(this.lblcentralNode);
            this.grbDataBaseSettings.Controls.Add(this.lblDBPassword);
            this.grbDataBaseSettings.Controls.Add(this.lblNode);
            this.grbDataBaseSettings.Controls.Add(this.lblDBUserName);
            this.grbDataBaseSettings.Controls.Add(this.lblStation);
            this.grbDataBaseSettings.Controls.Add(this.lblDataBaseName);
            this.grbDataBaseSettings.Controls.Add(this.lblDBServerName);
            this.grbDataBaseSettings.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grbDataBaseSettings.Location = new System.Drawing.Point(0, 0);
            this.grbDataBaseSettings.Name = "grbDataBaseSettings";
            this.grbDataBaseSettings.Size = new System.Drawing.Size(616, 353);
            this.grbDataBaseSettings.TabIndex = 1;
            this.grbDataBaseSettings.TabStop = false;
            this.grbDataBaseSettings.Text = "DataBase Settings";
            // 
            // ControlAttachmentPrint
            // 
            this.ControlAttachmentPrint.AutoSize = true;
            this.ControlAttachmentPrint.Checked = true;
            this.ControlAttachmentPrint.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ControlAttachmentPrint.Location = new System.Drawing.Point(326, 215);
            this.ControlAttachmentPrint.Name = "ControlAttachmentPrint";
            this.ControlAttachmentPrint.Size = new System.Drawing.Size(140, 17);
            this.ControlAttachmentPrint.TabIndex = 116;
            this.ControlAttachmentPrint.Text = "Control Attachment Print";
            this.ControlAttachmentPrint.UseVisualStyleBackColor = true;
            // 
            // AutoGenerateDeliveryOrder
            // 
            this.AutoGenerateDeliveryOrder.AutoSize = true;
            this.AutoGenerateDeliveryOrder.Location = new System.Drawing.Point(486, 169);
            this.AutoGenerateDeliveryOrder.Name = "AutoGenerateDeliveryOrder";
            this.AutoGenerateDeliveryOrder.Size = new System.Drawing.Size(114, 17);
            this.AutoGenerateDeliveryOrder.TabIndex = 115;
            this.AutoGenerateDeliveryOrder.Text = "Auto Generate DO";
            this.AutoGenerateDeliveryOrder.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AutoGenerateDeliveryOrder.UseVisualStyleBackColor = true;
            // 
            // ControlDepositSourceConsistency
            // 
            this.ControlDepositSourceConsistency.AutoSize = true;
            this.ControlDepositSourceConsistency.Checked = true;
            this.ControlDepositSourceConsistency.CheckState = System.Windows.Forms.CheckState.Checked;
            this.ControlDepositSourceConsistency.Location = new System.Drawing.Point(326, 192);
            this.ControlDepositSourceConsistency.Name = "ControlDepositSourceConsistency";
            this.ControlDepositSourceConsistency.Size = new System.Drawing.Size(195, 17);
            this.ControlDepositSourceConsistency.TabIndex = 114;
            this.ControlDepositSourceConsistency.Text = "Control Deposit Source Consistency";
            this.ControlDepositSourceConsistency.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ControlDepositSourceConsistency.UseVisualStyleBackColor = true;
            // 
            // PrinterName
            // 
            this.PrinterName.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.PrinterName.FormattingEnabled = true;
            this.PrinterName.Location = new System.Drawing.Point(130, 279);
            this.PrinterName.Name = "PrinterName";
            this.PrinterName.Size = new System.Drawing.Size(183, 21);
            this.PrinterName.TabIndex = 48;
            // 
            // DataBaseType
            // 
            this.DataBaseType.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.DataBaseType.Enabled = false;
            this.DataBaseType.FormattingEnabled = true;
            this.DataBaseType.Items.AddRange(new object[] {
            "Oracle",
            "MySql"});
            this.DataBaseType.Location = new System.Drawing.Point(130, 34);
            this.DataBaseType.Name = "DataBaseType";
            this.DataBaseType.Size = new System.Drawing.Size(124, 21);
            this.DataBaseType.TabIndex = 1;
            // 
            // lblDataBaseType
            // 
            this.lblDataBaseType.Location = new System.Drawing.Point(11, 37);
            this.lblDataBaseType.Name = "lblDataBaseType";
            this.lblDataBaseType.Size = new System.Drawing.Size(113, 13);
            this.lblDataBaseType.TabIndex = 100;
            this.lblDataBaseType.Text = "Data Base Type";
            this.lblDataBaseType.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // AllowDeliveryOrderPrinting
            // 
            this.AllowDeliveryOrderPrinting.AutoSize = true;
            this.AllowDeliveryOrderPrinting.Location = new System.Drawing.Point(326, 169);
            this.AllowDeliveryOrderPrinting.Name = "AllowDeliveryOrderPrinting";
            this.AllowDeliveryOrderPrinting.Size = new System.Drawing.Size(66, 17);
            this.AllowDeliveryOrderPrinting.TabIndex = 14;
            this.AllowDeliveryOrderPrinting.Text = "Print DO";
            this.AllowDeliveryOrderPrinting.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.AllowDeliveryOrderPrinting.UseVisualStyleBackColor = true;
            this.AllowDeliveryOrderPrinting.CheckedChanged += new System.EventHandler(this.AllowDeliveryOrderPrinting_CheckedChanged);
            // 
            // AutoGenerateDocumentNumber
            // 
            this.AutoGenerateDocumentNumber.AutoSize = true;
            this.AutoGenerateDocumentNumber.Checked = true;
            this.AutoGenerateDocumentNumber.CheckState = System.Windows.Forms.CheckState.Checked;
            this.AutoGenerateDocumentNumber.Location = new System.Drawing.Point(486, 146);
            this.AutoGenerateDocumentNumber.Name = "AutoGenerateDocumentNumber";
            this.AutoGenerateDocumentNumber.Size = new System.Drawing.Size(118, 17);
            this.AutoGenerateDocumentNumber.TabIndex = 14;
            this.AutoGenerateDocumentNumber.Text = "Auto Generate Doc";
            this.AutoGenerateDocumentNumber.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.AutoGenerateDocumentNumber.UseVisualStyleBackColor = true;
            // 
            // allowNegativeStock
            // 
            this.allowNegativeStock.AutoSize = true;
            this.allowNegativeStock.Location = new System.Drawing.Point(326, 146);
            this.allowNegativeStock.Name = "allowNegativeStock";
            this.allowNegativeStock.Size = new System.Drawing.Size(128, 17);
            this.allowNegativeStock.TabIndex = 13;
            this.allowNegativeStock.Text = "Allow Negative Stock";
            this.allowNegativeStock.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.allowNegativeStock.UseVisualStyleBackColor = true;
            // 
            // LogChangeScripts
            // 
            this.LogChangeScripts.AutoSize = true;
            this.LogChangeScripts.Checked = true;
            this.LogChangeScripts.CheckState = System.Windows.Forms.CheckState.Checked;
            this.LogChangeScripts.Location = new System.Drawing.Point(29, 316);
            this.LogChangeScripts.Name = "LogChangeScripts";
            this.LogChangeScripts.Size = new System.Drawing.Size(119, 17);
            this.LogChangeScripts.TabIndex = 46;
            this.LogChangeScripts.Text = "Log Change Scripts";
            this.LogChangeScripts.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.LogChangeScripts.UseVisualStyleBackColor = true;
            // 
            // cmdEasyMoveWarningFolder
            // 
            this.cmdEasyMoveWarningFolder.Location = new System.Drawing.Point(291, 251);
            this.cmdEasyMoveWarningFolder.Name = "cmdEasyMoveWarningFolder";
            this.cmdEasyMoveWarningFolder.Size = new System.Drawing.Size(26, 20);
            this.cmdEasyMoveWarningFolder.TabIndex = 9;
            this.cmdEasyMoveWarningFolder.Text = "...";
            this.cmdEasyMoveWarningFolder.UseVisualStyleBackColor = true;
            this.cmdEasyMoveWarningFolder.Click += new System.EventHandler(this.cmdWarningFolder_Click);
            // 
            // DBPort
            // 
            this.DBPort.Location = new System.Drawing.Point(130, 164);
            this.DBPort.Name = "DBPort";
            this.DBPort.PasswordChar = '|';
            this.DBPort.Size = new System.Drawing.Size(69, 20);
            this.DBPort.TabIndex = 6;
            // 
            // cmdEasyMoveScriptFolder
            // 
            this.cmdEasyMoveScriptFolder.Location = new System.Drawing.Point(291, 201);
            this.cmdEasyMoveScriptFolder.Name = "cmdEasyMoveScriptFolder";
            this.cmdEasyMoveScriptFolder.Size = new System.Drawing.Size(26, 20);
            this.cmdEasyMoveScriptFolder.TabIndex = 7;
            this.cmdEasyMoveScriptFolder.Text = "...";
            this.cmdEasyMoveScriptFolder.UseVisualStyleBackColor = true;
            this.cmdEasyMoveScriptFolder.Click += new System.EventHandler(this.cmdScriptFolder_Click);
            // 
            // cmdEasyMoveErrFolder
            // 
            this.cmdEasyMoveErrFolder.Location = new System.Drawing.Point(291, 226);
            this.cmdEasyMoveErrFolder.Name = "cmdEasyMoveErrFolder";
            this.cmdEasyMoveErrFolder.Size = new System.Drawing.Size(26, 20);
            this.cmdEasyMoveErrFolder.TabIndex = 8;
            this.cmdEasyMoveErrFolder.Text = "...";
            this.cmdEasyMoveErrFolder.UseVisualStyleBackColor = true;
            this.cmdEasyMoveErrFolder.Click += new System.EventHandler(this.cmdErrFolder_Click);
            // 
            // lblDBPort
            // 
            this.lblDBPort.Location = new System.Drawing.Point(26, 167);
            this.lblDBPort.Name = "lblDBPort";
            this.lblDBPort.Size = new System.Drawing.Size(94, 17);
            this.lblDBPort.TabIndex = 106;
            this.lblDBPort.Text = "Port";
            this.lblDBPort.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // cmdSettingSave
            // 
            this.cmdSettingSave.Location = new System.Drawing.Point(411, 304);
            this.cmdSettingSave.Name = "cmdSettingSave";
            this.cmdSettingSave.Size = new System.Drawing.Size(125, 38);
            this.cmdSettingSave.TabIndex = 16;
            this.cmdSettingSave.Text = "Save";
            this.cmdSettingSave.UseVisualStyleBackColor = true;
            this.cmdSettingSave.Click += new System.EventHandler(this.cmdSettingSave_Click);
            // 
            // cmdSettingTest
            // 
            this.cmdSettingTest.Location = new System.Drawing.Point(397, 251);
            this.cmdSettingTest.Name = "cmdSettingTest";
            this.cmdSettingTest.Size = new System.Drawing.Size(156, 42);
            this.cmdSettingTest.TabIndex = 15;
            this.cmdSettingTest.Text = "Test";
            this.cmdSettingTest.UseVisualStyleBackColor = true;
            this.cmdSettingTest.Click += new System.EventHandler(this.cmdSettingTest_Click);
            // 
            // WarningDir
            // 
            this.WarningDir.Location = new System.Drawing.Point(130, 252);
            this.WarningDir.Name = "WarningDir";
            this.WarningDir.ReadOnly = true;
            this.WarningDir.Size = new System.Drawing.Size(158, 20);
            this.WarningDir.TabIndex = 41;
            this.WarningDir.TabStop = false;
            // 
            // ErrorDir
            // 
            this.ErrorDir.Location = new System.Drawing.Point(130, 227);
            this.ErrorDir.Name = "ErrorDir";
            this.ErrorDir.ReadOnly = true;
            this.ErrorDir.Size = new System.Drawing.Size(158, 20);
            this.ErrorDir.TabIndex = 39;
            this.ErrorDir.TabStop = false;
            // 
            // DBPassword
            // 
            this.DBPassword.Location = new System.Drawing.Point(130, 137);
            this.DBPassword.Name = "DBPassword";
            this.DBPassword.PasswordChar = '*';
            this.DBPassword.Size = new System.Drawing.Size(142, 20);
            this.DBPassword.TabIndex = 5;
            // 
            // DBUserName
            // 
            this.DBUserName.Location = new System.Drawing.Point(130, 111);
            this.DBUserName.Name = "DBUserName";
            this.DBUserName.PasswordChar = '|';
            this.DBUserName.Size = new System.Drawing.Size(142, 20);
            this.DBUserName.TabIndex = 4;
            // 
            // DataBaseName
            // 
            this.DataBaseName.Location = new System.Drawing.Point(130, 85);
            this.DataBaseName.Name = "DataBaseName";
            this.DataBaseName.PasswordChar = '|';
            this.DataBaseName.Size = new System.Drawing.Size(142, 20);
            this.DataBaseName.TabIndex = 3;
            // 
            // MRCnumber
            // 
            this.MRCnumber.Location = new System.Drawing.Point(411, 107);
            this.MRCnumber.Name = "MRCnumber";
            this.MRCnumber.Size = new System.Drawing.Size(142, 20);
            this.MRCnumber.TabIndex = 12;
            // 
            // centralNode
            // 
            this.centralNode.Location = new System.Drawing.Point(411, 81);
            this.centralNode.Name = "centralNode";
            this.centralNode.Size = new System.Drawing.Size(142, 20);
            this.centralNode.TabIndex = 12;
            // 
            // Node
            // 
            this.Node.Location = new System.Drawing.Point(411, 55);
            this.Node.Name = "Node";
            this.Node.Size = new System.Drawing.Size(142, 20);
            this.Node.TabIndex = 11;
            // 
            // Station
            // 
            this.Station.Location = new System.Drawing.Point(411, 29);
            this.Station.Name = "Station";
            this.Station.Size = new System.Drawing.Size(142, 20);
            this.Station.TabIndex = 10;
            // 
            // DBServerName
            // 
            this.DBServerName.Location = new System.Drawing.Point(130, 59);
            this.DBServerName.Name = "DBServerName";
            this.DBServerName.Size = new System.Drawing.Size(142, 20);
            this.DBServerName.TabIndex = 2;
            this.DBServerName.Text = "localhost";
            // 
            // ScriptDir
            // 
            this.ScriptDir.Location = new System.Drawing.Point(130, 202);
            this.ScriptDir.Name = "ScriptDir";
            this.ScriptDir.ReadOnly = true;
            this.ScriptDir.Size = new System.Drawing.Size(158, 20);
            this.ScriptDir.TabIndex = 37;
            this.ScriptDir.TabStop = false;
            // 
            // lblPrinterName
            // 
            this.lblPrinterName.Location = new System.Drawing.Point(11, 280);
            this.lblPrinterName.Name = "lblPrinterName";
            this.lblPrinterName.Size = new System.Drawing.Size(113, 13);
            this.lblPrinterName.TabIndex = 110;
            this.lblPrinterName.Text = "Printer";
            this.lblPrinterName.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lblWarningDir
            // 
            this.lblWarningDir.Location = new System.Drawing.Point(11, 255);
            this.lblWarningDir.Name = "lblWarningDir";
            this.lblWarningDir.Size = new System.Drawing.Size(113, 13);
            this.lblWarningDir.TabIndex = 109;
            this.lblWarningDir.Text = "Warning Log Directory";
            this.lblWarningDir.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lblErrorDir
            // 
            this.lblErrorDir.Location = new System.Drawing.Point(11, 230);
            this.lblErrorDir.Name = "lblErrorDir";
            this.lblErrorDir.Size = new System.Drawing.Size(113, 13);
            this.lblErrorDir.TabIndex = 108;
            this.lblErrorDir.Text = "Error Log Directory";
            this.lblErrorDir.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lblMRCnumber
            // 
            this.lblMRCnumber.Location = new System.Drawing.Point(309, 110);
            this.lblMRCnumber.Name = "lblMRCnumber";
            this.lblMRCnumber.Size = new System.Drawing.Size(92, 13);
            this.lblMRCnumber.TabIndex = 113;
            this.lblMRCnumber.Text = "MRC Number";
            this.lblMRCnumber.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lblScriptDir
            // 
            this.lblScriptDir.Location = new System.Drawing.Point(11, 205);
            this.lblScriptDir.Name = "lblScriptDir";
            this.lblScriptDir.Size = new System.Drawing.Size(113, 13);
            this.lblScriptDir.TabIndex = 107;
            this.lblScriptDir.Text = "Script Log Directory";
            this.lblScriptDir.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lblcentralNode
            // 
            this.lblcentralNode.Location = new System.Drawing.Point(309, 84);
            this.lblcentralNode.Name = "lblcentralNode";
            this.lblcentralNode.Size = new System.Drawing.Size(92, 13);
            this.lblcentralNode.TabIndex = 113;
            this.lblcentralNode.Text = "Central  Station";
            this.lblcentralNode.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lblDBPassword
            // 
            this.lblDBPassword.Location = new System.Drawing.Point(26, 140);
            this.lblDBPassword.Name = "lblDBPassword";
            this.lblDBPassword.Size = new System.Drawing.Size(98, 13);
            this.lblDBPassword.TabIndex = 105;
            this.lblDBPassword.Text = "Password";
            this.lblDBPassword.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lblNode
            // 
            this.lblNode.Location = new System.Drawing.Point(323, 58);
            this.lblNode.Name = "lblNode";
            this.lblNode.Size = new System.Drawing.Size(78, 13);
            this.lblNode.TabIndex = 112;
            this.lblNode.Text = "Node";
            this.lblNode.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lblDBUserName
            // 
            this.lblDBUserName.Location = new System.Drawing.Point(26, 114);
            this.lblDBUserName.Name = "lblDBUserName";
            this.lblDBUserName.Size = new System.Drawing.Size(98, 13);
            this.lblDBUserName.TabIndex = 104;
            this.lblDBUserName.Text = "User Name";
            this.lblDBUserName.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lblStation
            // 
            this.lblStation.Location = new System.Drawing.Point(323, 32);
            this.lblStation.Name = "lblStation";
            this.lblStation.Size = new System.Drawing.Size(78, 13);
            this.lblStation.TabIndex = 111;
            this.lblStation.Text = "Sation";
            this.lblStation.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lblDataBaseName
            // 
            this.lblDataBaseName.Location = new System.Drawing.Point(26, 88);
            this.lblDataBaseName.Name = "lblDataBaseName";
            this.lblDataBaseName.Size = new System.Drawing.Size(98, 13);
            this.lblDataBaseName.TabIndex = 103;
            this.lblDataBaseName.Text = "DataBase Name";
            this.lblDataBaseName.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lblDBServerName
            // 
            this.lblDBServerName.Location = new System.Drawing.Point(23, 62);
            this.lblDBServerName.Name = "lblDBServerName";
            this.lblDBServerName.Size = new System.Drawing.Size(97, 13);
            this.lblDBServerName.TabIndex = 101;
            this.lblDBServerName.Text = "Server Name";
            this.lblDBServerName.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // LDAPAuthenticated
            // 
            this.LDAPAuthenticated.AutoSize = true;
            this.LDAPAuthenticated.Location = new System.Drawing.Point(190, 316);
            this.LDAPAuthenticated.Name = "LDAPAuthenticated";
            this.LDAPAuthenticated.Size = new System.Drawing.Size(123, 17);
            this.LDAPAuthenticated.TabIndex = 117;
            this.LDAPAuthenticated.Text = "LDAP Authenticated";
            this.LDAPAuthenticated.UseVisualStyleBackColor = true;
            this.LDAPAuthenticated.CheckedChanged += new System.EventHandler(this.LDAPAuthenticated_CheckedChanged);
            // 
            // frmsettings
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(616, 353);
            this.Controls.Add(this.grbDataBaseSettings);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmsettings";
            this.Text = "Data Base and Directory Settings";
            this.Load += new System.EventHandler(this.frmsettings_Load);
            this.grbDataBaseSettings.ResumeLayout(false);
            this.grbDataBaseSettings.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.GroupBox grbDataBaseSettings;
        private System.Windows.Forms.FolderBrowserDialog folderBrowserDialog1;
        private System.Windows.Forms.Button cmdEasyMoveWarningFolder;
        private System.Windows.Forms.Button cmdEasyMoveScriptFolder;
        private System.Windows.Forms.Button cmdEasyMoveErrFolder;
        private System.Windows.Forms.TextBox DBPort;
        private System.Windows.Forms.Label lblDBPort;
        private System.Windows.Forms.Button cmdSettingSave;
        private System.Windows.Forms.Button cmdSettingTest;
        private System.Windows.Forms.TextBox WarningDir;
        private System.Windows.Forms.TextBox ErrorDir;
        private System.Windows.Forms.TextBox DBPassword;
        private System.Windows.Forms.TextBox DBUserName;
        private System.Windows.Forms.TextBox DataBaseName;
        private System.Windows.Forms.TextBox DBServerName;
        private System.Windows.Forms.TextBox ScriptDir;
        private System.Windows.Forms.Label lblPrinterName;
        private System.Windows.Forms.Label lblWarningDir;
        private System.Windows.Forms.Label lblErrorDir;
        private System.Windows.Forms.Label lblScriptDir;
        private System.Windows.Forms.Label lblDBPassword;
        private System.Windows.Forms.Label lblDBUserName;
        private System.Windows.Forms.Label lblDataBaseName;
        private System.Windows.Forms.Label lblDBServerName;
        private System.Windows.Forms.CheckBox LogChangeScripts;
        private System.Windows.Forms.Label lblDataBaseType;
        private System.Windows.Forms.ComboBox DataBaseType;
        private System.Windows.Forms.ComboBox PrinterName;
        private System.Windows.Forms.TextBox centralNode;
        private System.Windows.Forms.TextBox Node;
        private System.Windows.Forms.TextBox Station;
        private System.Windows.Forms.Label lblcentralNode;
        private System.Windows.Forms.Label lblNode;
        private System.Windows.Forms.Label lblStation;
        private System.Windows.Forms.CheckBox AutoGenerateDocumentNumber;
        private System.Windows.Forms.CheckBox allowNegativeStock;
        private System.Windows.Forms.TextBox MRCnumber;
        private System.Windows.Forms.Label lblMRCnumber;
        private System.Windows.Forms.CheckBox AllowDeliveryOrderPrinting;
        private System.Windows.Forms.CheckBox ControlDepositSourceConsistency;
        private System.Windows.Forms.CheckBox AutoGenerateDeliveryOrder;
        private System.Windows.Forms.CheckBox ControlAttachmentPrint;
        private System.Windows.Forms.CheckBox LDAPAuthenticated;
    }
}